# users GitHub php-actions:
# - https://github.com/php-actions/composer
# - https://github.com/php-actions/phpunit

name: static CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '42 5 * * *'

jobs:
  ci_static:
    # only run jobs via scheduled workflow in main repo, not in forks
    if: (github.event_name == 'schedule' && github.repository == 'sypets/osbibx-parser') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHPUnit tests
          uses: php-actions/phpunit@v3
          with:
            configuration: "build/phpunit.xml"
            memory_limit: "256M"

      - name: "composer validate"
        run: composer validate

      - name: "composer install"
        run: composer install

      - name: "php-cs-fixer"
        run: php vendor/bin/php-cs-fixer fix --dry-run -v --config ./build/php-cs-fixer.php src

      - name: "lint"
        run: find src -name *.php -print0 | xargs -0 -n1 -P4 php -dxdebug.mode=off -l

      - name: "phpstan"
        run: vendor/bin/phpstan analyse --no-progress --no-interaction --memory-limit 4G -c build/phpstan.neon
